apiVersion: v1
kind: Service
metadata:
  name: blog-service
spec:
  selector:
    app: blog
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  labels:
    purpose: blog
spec:
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: app/blog:latest
        #imagePullPolicy: Never
        env:
        - name: PGPASSWORD
          value: blog_backend
        - name: PGUSER
          value: blog_backend
        - name: PGDATABASE
          value: blog_backend
        - name: PGHOST
          value: postgresql-service.default.svc.cluster.local
        ports:
          - containerPort: 3000