apiVersion: v1
kind: Service
metadata:
  name: blog-service
spec:
  selector:
    app: blog
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  labels:
    purpose: blog
spec:
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: jakubnajman/blog_app:latest
        env:
        - name: POSTGRES_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: dbsecret
              key: DATABASE_PASSWORD
        - name: POSTGRES_USER
          valueFrom: 
            secretKeyRef:
              name: dbsecret
              key: DATABASE_USERNAME
        - name: POSTGRES_DB
          valueFrom: 
            secretKeyRef:
              name: dbsecret
              key: DATABASE_NAME
        - name: PGHOST
          valueFrom: 
            secretKeyRef:
              name: dbsecret
              key: DATABASE_HOST
        ports:
          - containerPort: 3000