version: '3'
services: 
  
  blog:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - '3000:3035'
    tty: true
    env_file: 
      - .env
    environment: 
      - PGHOST=db
      - PGUSER=blog_backend
      - PGDATABASE=blog_backend
      - PGPASSWORD=blog_backend
    links:
      - db

  redis:
    image: 'redis:latest'
  
  db:
    image: 'postgres:latest'
    restart: always
    environment: 
      - POSTGRES_PASSWORD=blog_backend
      - POSTGRES_USER=blog_backend
      - POSTGRES_DATABASE=blog_backend
