version: '3'
services: 
  db:
    image: 'postgres:latest'
    restart: always
    environment: 
      - POSTGRES_PASSWORD=blog_backend
      - POSTGRES_USER=blog_backend
      - POSTGRES_DB=blog_backend

  blog:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - '3000:3000'
    tty: true
    environment: 
      - PGHOST=db
      - PGUSER=blog_backend
      - PGDATABASE=blog_backend
      - PGPASSWORD=blog_backend
    links:
      - redis
      - db

  redis:
    image: 'redis:latest'
  
  
