node{
    // def IVER = sh (script: "git rev-parse --short HEAD", returnStdout: true)
    def DATABASE_HOST='postgresql-service.default.svc.cluster.local'
    def DATABASE_NAME='blog_backend'
    def DATABASE_PASSWORD='blog_backend'
    def DATABASE_USERNAME='blog_backend'

    stage('Clone repository'){
        checkout scm
        sh 'echo Repository cloned'
        sh 'git status'
    }
    stage('Building app'){
        sh """
            cd blog
            export IVER="latest"
            docker-compose build
            docker-compose push blog
        """
        sh 'echo App builded.'
    }
    stage('Test image'){
        sh 'echo Test passed.'
    }
    stage('Deploying on Kubernetes'){
        sh 'eval $(minikube docker-env)'
        sh """
            cd blog/kube
            export IVER="latest"
            export DATABASE_HOST=${DATABASE_HOST}
            export DATABASE_NAME=${DATABASE_NAME}
            export DATABASE_PASSWORD=${DATABASE_PASSWORD}
            export DATABASE_USERNAME=${DATABASE_USERNAME}
            envsubst < blogKube.yaml > blog_changed.yaml
            kubectl apply -f blog_changed.yaml
        """
        sh 'cd blog/kube && kubectl apply -f addit/'
        sh 'echo Deployments and services aplied.'
    }
}